create or replace TABLE DEMO.LEADS_SCORED_SCH.LEADS_SCORED (
	PREDICT NUMBER(38,0),
	P0 NUMBER(10,8),
	P1 NUMBER(10,8),
	MAILCHIMP_ID NUMBER(38,0),
	USER_FULL_NAME VARCHAR(255),
	USER_EMAIL VARCHAR(255),
	MEMBER_RATING NUMBER(38,0),
	COUNTRY_CODE VARCHAR(20),
	MADE_PURCHASE NUMBER(38,0),
	OPTIN_DAYS NUMBER(38,0),
	EMAIL_PROVIDER VARCHAR(255)
);
